better than it was before
Interlisp/Interlisp.github.io pull request #190
Opened 2023-12-12 00:56 UTC by masinter

2023-12-12 05:29 UTC, stumbo requested changes

2023-12-12 05:29 UTC, stumbo commented on content/en/project/_index.md
> +The 1970s and 80s saw major advances in computing and Human-Computer interaction.  At Xerox PARC there were four IDEs developed with different approaches: Smalltalk, with an object-oriented system; I
three IDEs developed? Or are you counting Cedar and Mesa as distinctly different.

2023-12-12 05:29 UTC, stumbo commented on content/en/project/_index.md
> +The 1970s and 80s saw major advances in computing and Human-Computer interaction.  At Xerox PARC there were four IDEs developed with different approaches: Smalltalk, with an object-oriented system; I
...infrastructure and vision **of** computing and distributed systems, ,,,

2023-12-12 05:29 UTC, stumbo commented on content/en/project/_index.md
> +We started with sources from Venue for a not-quite-finished release of what was to be Medley 3.5.
This is repeating what we say earlier.

2023-12-12 05:29 UTC, stumbo commented on content/en/project/_index.md
> +The Medley Interlisp Project was created to revive the "Interlisp experience" by creating an environment that could be used by (and might even be useful for) modern users. Starting from the 20-year-o
could be used -> can be used

in the current environment -> in today's environment

Is open source an activity or was it the impetus that has allowed the activity of reviving Medley Interlisp to go forward?

2023-12-14 13:09 UTC, stumbo commented
Superseded by #194?

2023-12-15 05:03 UTC, masinter commented
superseded also

2023-12-15 05:03 UTC, closed without merging