Restructuring the donactions section of the Get Involved page
Interlisp/Interlisp.github.io pull request #223
Opened 2024-05-04 11:49 UTC by pamoroso

The patch restructures the donations section of the [Get Involved](https://interlisp.org/project/getinvolved/) page as a list. This way the options stand out more and make up a template for expansion to more donation methods.

2024-05-04 23:41 UTC, masinter commented
When setting up Paypal Interlisp they offer a PayPal Giving donation form.
I started to set that up but was out of time.
In gathering the info for explaining this, I finished a Paypal donation page.

I'm wondering about making a separate page for donations.

https://interlisp.org/donate

would include all of the information about how to donate and why.
(I'd probably put it in /content/en/donate.md with an alias of /donate

and then changing all of the donate buttons to point there.
)


https://www.paypal.com/donate/?hosted_button_id=X69XCWJ6SJKUG
```
<form action="https://www.paypal.com/donate" method="post" target="_top">
<input type="hidden" name="hosted_button_id" value="X69XCWJ6SJKUG" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>
```

2024-05-04 23:42 UTC, masinter requested changes
i think a separate page would be better.

https://interlisp.org/donate

2024-05-05 19:21 UTC, pamoroso commented
Agreed, adding a separate donations page is a good idea and I can take care of that.

Is this code for embedding the donation batton into the page?

```
<form action="https://www.paypal.com/donate" method="post" target="_top">
<input type="hidden" name="hosted_button_id" value="X69XCWJ6SJKUG" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>
```

2024-05-05 21:50 UTC, stumbo commented
> Agreed, adding a separate donations page is a good idea and I can take care of that.
> 
> Is this code for embedding the donation batton into the page?
> 
> ```
> <form action="https://www.paypal.com/donate" method="post" target="_top">
> <input type="hidden" name="hosted_button_id" value="X69XCWJ6SJKUG" />
> <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
> <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
> </form>
> ```

Yes - this will create a yellow 'pill' style button with the word Donate in it:
![image](https://github.com/Interlisp/Interlisp.github.io/assets/22384842/709dff1f-4c8a-4a2d-bfb6-17908ad77e8d)

2024-05-05 23:04 UTC, Anzus commented
For those interested in making a donation via corporate route (which sometimes includes matching) InterlispOrg can be found on the Benevity portal by either searching for “Interlisp” or the org numbered 840-872528093.

> On May 5, 2024, at 4:50 PM, Bill Stumbo ***@***.***> wrote:
> 
> 
> Agreed, adding a separate donations page is a good idea and I can take care of that.
> Is this code for embedding the donation batton into the page?
> <form action="https://www.paypal.com/donate" method="post" target="_top">
> <input type="hidden" name="hosted_button_id" value="X69XCWJ6SJKUG" />
> <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
> <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
> </form>
> 
> Yes - this will create a yellow 'pill' style button with the word Donate in it:
> image.png (view on web)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-05-06 07:00 UTC, pamoroso commented
Is [this](https://benevity.com) the Benevity portal? The only search option I found, the magnifying glass icon at the top right of the page, seems to be just for site searches and not for searching organizations.

2024-05-06 12:08 UTC, Anzus commented
No, any company that uses Benevity gets it's own private portal unique to that entity, tied to the company SSO and/or the payroll system.On May 6, 2024 2:00 AM, Paolo Amoroso ***@***.***> wrote:
Is this the Benevity portal? The only search option I found, the magnifying glass icon at the top right of the page, seems to be just for site searches and not for searching organizations.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-05-07 10:35 UTC, pamoroso commented
I updated the PR with a draft of the new donations page. In addition to your feedback there are a few things to change and decide.

What's the most appropriate weight of the new page, if any?

I'd like to link the donations page from [Get Involved](https://interlisp.org/project/getinvolved): what's the path to use in the link? `/donate`? Similarly, is `/project/organization` the path for linking [Organization](https://interlisp.org/project/organization) from the donations page?

2024-05-08 11:14 UTC, stumbo requested changes

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
Naming it `donate` makes it unreachable from any of the existing pages.  The page hierarchy has has three visible branches from our home page `project`, `software` and `history`.  It needs to be hung off one of those to show up.

I'd suggest moving it into the `project` folder.  It will then appear as a selection when the user is in the project portion of the web pages.

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
> +InterlispOrg Inc, the non-profit which runs the Medley Interlisp Project, uses donations to pay for online services, web hosting; larger donations for hiring consultants and contract workers to help
Replace this with the text at line 29 and remove lines 26 on.

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
> +## How to donate
Retitle this to **Other donation methods**

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
> +<form action="https://www.paypal.com/donate" method="post" target="_top">
Move this to be below line 9 - so, we have the text about being a non-profit, followed immediately be the donate button.

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
> +- [PayPal](https://www.paypal.com/donate/?hosted_button_id=MCHS5GWLVYLUY): use the donation button above or send directly to [paypal@interlisp.org](mailto:paypal@interlisp.org)
Delete this, it duplicates the donation button.

2024-05-08 11:14 UTC, stumbo commented on content/en/donate.md
> +
Delete the remaining text.

2024-05-08 11:14 UTC, stumbo commented on content/en/project/getInvolved/_index.md
> +## 6. Donations
Delete all of this, it will be covered in the donations page.

2024-05-08 12:35 UTC, pamoroso commented on content/en/project/getInvolved/_index.md
> +## 6. Donations
What about line 17? Should I remove it too or change the link to point to the new donations page (`/project/donate`)?

> `6. [Send us a donation](https://github.com/sponsors/Interlisp).`

2024-05-08 12:37 UTC, pamoroso commented on content/en/donate.md
The `project` folder looks good but I need to figure how to move a file via the GitHub web interface I used for this PR, which doesn't seem to be possible other than by removing the file and recreating it at the right place.

2024-05-08 12:41 UTC, pamoroso commented on content/en/donate.md
> +
Not sure I understand. Do you mean removing the donations team and Benevity items altogether? Or removing from `## Tax deducibility` onward?

2024-05-09 17:59 UTC, pamoroso commented on content/en/donate.md
Based on the discussion in the May 8, 2024 external meeting should the location of the new donations page still be `/content/en/project/donate.md`?

2024-05-09 18:21 UTC, masinter commented on content/en/donate.md
I'm not entirely sure what @stumbo has in mind, but if you save put the description at
`content/en/project/donate.md` and also add

```
aliases:
 - /donate
```
in the initial header of the donate.md page, (I think) that will result in the short form  https://interlisp.org/donate/ URL will redirect to the project/donate/ URL.

----
It is awkward to work on the web site using only the github editor, because there is no way to move files around or test the results of edits without deploying them -- you really need a local install of 'hugo' to do that.

2024-05-10 11:25 UTC, stumbo commented on content/en/donate.md
@masinter Yes that will work.  I was more concerned that the current name of the page would isolate it and make it unreachable.  

---

Based on our Wednesday discussion, I'm rethinking the whole donate page.  I wonder if we should take two approaches.  One, put a donate button or icon on the footer of each page.  Something along the lines of this:  
 

![](https://github.com/Interlisp/Interlisp.github.io/assets/22384842/42e2a441-59b5-4470-b0a1-6a4dbfc43797)

I'm not sure I like the icon, but it's what was readily available.  We could link the icon directly to the Paypal donate page.  Secondly, we have a donate page, roughly the one Paolo has created that lives in the project hierarchy and holds information on the organization and all available donation options.

2024-05-10 20:19 UTC, pamoroso commented on content/en/donate.md
To proceed with creating the donate page I need clarification on [this](https://github.com/Interlisp/Interlisp.github.io/pull/223#discussion_r1593966467) and [this](https://github.com/Interlisp/Interlisp.github.io/pull/223#discussion_r1593958508).

2024-05-11 04:35 UTC, stumbo commented
See #225 for a proposed update to this PR.

2024-05-11 12:07 UTC, pamoroso commented
PS #225 supersedes #223, so the latter may be closed.

2024-05-11 12:21 UTC, closed without merging