Adding links to ELS 2024 talk and Alex Schroeder's post
Interlisp/Interlisp.github.io pull request #226
Opened 2024-05-13 10:34 UTC by pamoroso

I suggest updating the [news section](https://interlisp.org/project/status/) of the project site with links to Andrew Sengul's ELS 2024 [video](https://www.twitch.tv/videos/2138739613?t=01h36m19s) and [paper](https://doi.org/10.5281/zenodo.11090093), and adding to the [comments section](https://interlisp.org/project/comments) a link to [Alex Schroeder's post](https://alexschroeder.ch/view/2024-05-11-distractions) on his impressions on Medley.

2024-05-13 11:23 UTC, stumbo requested changes

2024-05-13 11:23 UTC, stumbo commented on content/en/project/status/_index.md
> +<iframe src="https://player.twitch.tv/?video=2138739613&time=1h36m21s&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>
Replace `parent=wwww.example.com` with `parent=www.interlisp.org`

2024-05-13 11:47 UTC, pamoroso commented on content/en/project/status/_index.md
> +<iframe src="https://player.twitch.tv/?video=2138739613&time=1h36m21s&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>
Done.

2024-05-14 03:16 UTC, stumbo approved these changes

2024-05-14 03:16 UTC, merged

2024-05-14 09:13 UTC, pamoroso commented
On the published page the Twitch player is broken and shows the error "connection denied from player.twitch.tv". I don't know what's wrong as I copied the exact iframe embed code Twitch provided and replaced www.example.com with www.interlisp.org.

2024-05-14 11:30 UTC, stumbo commented
I suspect the problem  has to do with this comment on the European Lisp Symposium website:

> The timezone of our schedule is UTC+2. The videos of the streams will stay online for two weeks on Twitch, but will also be available on our [YouTube channel](https://www.youtube.com/@EuropeanLispSymposium). See you online!

It's not available in YouTube yet -- my suggestion is to remove the embedded video page and when the video becomes available through YouTube we can add it back in through YouTube.

2024-05-14 11:44 UTC, pamoroso commented
Makes sense, I submitte PR #227 to remove the video embed.