Publication of LOOPS book 1 by Stephen Kaisler
Interlisp/Interlisp.github.io pull request #244
Opened 2024-10-10 10:23 UTC by pamoroso

This change lists on the [Documentation](https://interlisp.org/software/using-medley#interlisp-books) page the LOOPS books by Stephen Kaisler and links to the first volume.

2024-10-11 04:08 UTC, masinter approved these changes
sh0uld this say "was an object extension of Interlisp" instead of "is"??

Somewhere there should be a mention of its role compared to CLOS and CommonLoops?
Possibly somewhere else, but raise that as an issue if you agree.

2024-10-11 06:44 UTC, pamoroso commented
I changed to "was an object extension of Interlisp".

2024-10-11 10:09 UTC, pamoroso commented
Concerning the role of LOOPS I raised [issue #1850](https://github.com/Interlisp/medley/issues/1850).

2024-10-13 04:08 UTC, stumbo requested changes

2024-10-13 04:08 UTC, stumbo commented on static/documentation/2024-loops-book-1.pdf.pdf
Rename to `static/documentation/2024-loops-book-1.pdf`  -- remove the extra `.pdf`

2024-10-13 06:48 UTC, pamoroso commented on static/documentation/2024-loops-book-1.pdf.pdf
Oops... Good catch, I didn't realize. Fixed.

2024-10-14 04:45 UTC, stumbo approved these changes

2024-10-14 04:46 UTC, merged